apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: vpn
        static_configs:
          - targets:
              - "vpn.app.svc.cluster.local:9001"

      - job_name: app
        static_configs:
          - targets:
              - "app.app.svc.cluster.local:9002"
