apiVersion: v1
kind: Secret
metadata:
  name: vpn-creds
  namespace: app
type: Opaque
stringData:
  creds.json: |
    {
      "creds": [
        {"username": "user1", "password": "pass1"},
        {"username": "user2", "password": "pass2"}
      ]
    }
