$ANSIBLE_VAULT;1.1;AES256
61343161323566343366363763383034336264333732623031376535356331393636353033383735
3862393130303338663633386261623430336137333162370a363661653063663731663838366462
31316464306565353063346164393931626331613161386539613162663436323034383734356234
3738333665376435630a306337393332383933633637613633643438306533366134363137323435
62323262643636316461323137653665353162343430616133613733343734343862353862303465
32376631386665636232306335313030623837396364613433373634383538306236386239326566
63653666326565346336393966323034616231663531343063386665633564383030393061613530
33613334393161306164643562373731356165343961333963613438373130356662323731383330
3861
