apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    http_port = 3000

    [security]
    admin_user = admin
    admin_password = admin

    [dashboards]
    default_home_dashboard_path = /etc/grafana/provisioning/dashboards/home.json

  dashboards.json: |
    {
      "annotations": { "list": [] },
      "editable": true,
      "schemaVersion": 36,
      "version": 1,
      "title": "VPN Metrics",
      "panels": [
        {
          "type": "timeseries",
          "title": "Allowed /status Requests (per second)",
          "targets": [
            {
              "expr": "irate(vpn_status_allowed_total[30s])",
              "legendFormat": "{{user}}",
              "refId": "A"
            }
          ],
          "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
          "options": {
            "showPoints": "never",
            "legend": { "displayMode": "table", "placement": "right" }
          }
        },
        {
          "type": "timeseries",
          "title": "Invalid JWT Requests (per second)",
          "targets": [
            {
              "expr": "irate(vpn_jwt_invalid_total[30s])",
              "refId": "A"
            }
          ],
          "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
          "options": {
            "showPoints": "never",
            "legend": { "displayMode": "table", "placement": "right" }
          }
        }
      ]
    }
